import { useCallback, useEffect, useMemo, useState } from "react";
import { get, newIdempotencyKey, post } from "@/api/client";
import { EmptyState } from "@/components/ui/EmptyState";
import { StatusTag, Tag } from "@/components/ui/StatusTag";
import type { DispatchPreviewDto, EmployeeDto, ProjectDto, ProjectRuntimeDto, ReceiptDto, WorkItemDto } from "@/types/api";

type DispatchRow={id:string;workItemId:string;workTitle:string;employeeId:string;employeeName:string;status:string;executionId:string|null;executionStatus:string|null};
type RuntimeItem={project:ProjectRuntimeDto["project"];work:WorkItemDto};
const button:React.CSSProperties={padding:"8px 14px",borderRadius:8,background:"var(--green)",color:"white",fontWeight:600};

export function DispatchPage(){
 const [items,setItems]=useState<RuntimeItem[]>([]);const [dispatches,setDispatches]=useState<DispatchRow[]>([]);const [employees,setEmployees]=useState<EmployeeDto[]>([]);const [preview,setPreview]=useState<DispatchPreviewDto|null>(null);const [review,setReview]=useState<{work:WorkItemDto;receipt:ReceiptDto}|null>(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [receiptSummary,setReceiptSummary]=useState("已完成工作项要求并完成自测");
 const load=useCallback(async()=>{const [projectsResult,dispatchResult,employeeResult]=await Promise.all([get<ProjectDto[]>("/projects"),get<DispatchRow[]>("/dispatches"),get<EmployeeDto[]>("/employees")]);const active=projectsResult.data.filter((p)=>p.status==="active");const runtimes=await Promise.all(active.map((p)=>get<ProjectRuntimeDto>(`/projects/${p.id}/runtime`)));setItems(runtimes.flatMap((r)=>r.data.workItems.map((work)=>({project:r.data.project,work}))));setDispatches(dispatchResult.data);setEmployees(employeeResult.data.filter((e)=>e.schedulable));},[]);
 useEffect(()=>{void load().catch((e:Error)=>setMessage(e.message));},[load]);
 const actionable=useMemo(()=>items.filter(({work})=>["pending_dispatch","running","review_pending"].includes(work.status)),[items]);
 const calculate=async(work:WorkItemDto)=>{setBusy(true);try{setPreview((await post<DispatchPreviewDto>(`/work-items/${work.id}/dispatch/preview`,{})).data);setMessage("候选计算完成；预览不会占用连接容量");}catch(e){setMessage(e instanceof Error?e.message:"候选计算失败");}finally{setBusy(false);}};
 const confirm=async()=>{if(!preview?.selectedEmployeeId)return;setBusy(true);try{await post(`/dispatches/${preview.dispatchId}/confirm`,{employeeId:preview.selectedEmployeeId},{"Idempotency-Key":newIdempotencyKey()});setPreview(null);await load();setMessage("派发已幂等确认，执行记录与容量租约已创建");}catch(e){setMessage(e instanceof Error?e.message:"确认失败");}finally{setBusy(false);}};
 const submitReceipt=async(work:WorkItemDto)=>{const dispatch=dispatches.find((d)=>d.workItemId===work.id&&d.status==="running");if(!dispatch?.executionId)return;setBusy(true);try{await post<ReceiptDto>(`/executions/${dispatch.executionId}/receipts`,{status:"completed",summary:receiptSummary,deliverables:[{type:"text",label:`${work.title}交付说明`,uri:`nomos://work-items/${work.id}/attempt-${work.attempt}`}],tests:[{name:"执行者自测",status:"passed",detail:"工作项要求已逐项检查"}],risks:[],nextActions:["等待人工验收"]});await load();setMessage("结构化回执已保存；工作项进入待验收，而不是直接完成");}catch(e){setMessage(e instanceof Error?e.message:"回执保存失败");}finally{setBusy(false);}};
 const openReview=async(work:WorkItemDto)=>{try{const receipts=await get<ReceiptDto[]>(`/work-items/${work.id}/receipts`);if(!receipts.data[0])throw new Error("未找到回执");setReview({work,receipt:receipts.data[0]});}catch(e){setMessage(e instanceof Error?e.message:"加载回执失败");}};
 const decide=async(result:"accepted"|"rework")=>{if(!review||!employees[0])return;setBusy(true);try{await post(`/receipts/${review.receipt.id}/acceptances`,{reviewerEmployeeId:employees[0].id,result,againstCriteria:review.work.acceptanceCriteriaSnapshot.map((criterion)=>({criterion,result:result==="accepted"?"passed":"failed",comment:result==="accepted"?"符合标准":"需要补充后重提"})),comment:result==="accepted"?"人工验收通过":"按验收标准返工"});setReview(null);await load();setMessage(result==="accepted"?"验收通过，后续依赖工作项已自动解锁":"已创建新 attempt，原回执与验收意见完整保留");}catch(e){setMessage(e instanceof Error?e.message:"验收失败");}finally{setBusy(false);}};
 return <div style={{padding:"28px 32px",overflow:"auto",height:"100%"}}><div style={{display:"flex",justifyContent:"space-between"}}><div><h1 style={{margin:0,fontSize:20}}>派发</h1><p style={{color:"var(--muted)"}}>先预览候选，再确认派发；Receipt 陈述执行事实，Acceptance 决定业务是否通过。</p></div><Tag variant="success">V0.0.3 · FE-501/502</Tag></div>{message?<p role="status" style={{padding:10,background:"var(--green-soft)",borderRadius:8}}>{message}</p>:null}
 {actionable.length===0?<EmptyState title="当前没有待处理工作项" description="启动项目或完成上游验收后，工作项会进入这里。"/>:<div style={{display:"grid",gap:10}}>{actionable.map(({project,work})=><article key={work.id} style={{display:"grid",gridTemplateColumns:"1.4fr 2fr 110px auto",gap:12,alignItems:"center",padding:16,background:"var(--paper)",borderRadius:12}}><div><strong>{work.title}</strong><div style={{fontSize:12,color:"var(--muted)"}}>{project.name} · attempt {work.attempt}</div></div><span>{work.requirements}</span><StatusTag type="workitem" status={work.status}/><div>{work.status==="pending_dispatch"?<button disabled={busy} onClick={()=>void calculate(work)} style={button}>预览候选</button>:null}{work.status==="running"?<div style={{display:"flex",gap:8}}><input aria-label={`${work.title}回执摘要`} value={receiptSummary} onChange={(e)=>setReceiptSummary(e.target.value)} style={{padding:7,border:"1px solid var(--line)",borderRadius:7}}/><button disabled={busy} onClick={()=>void submitReceipt(work)} style={button}>提交回执</button></div>:null}{work.status==="review_pending"?<button onClick={()=>void openReview(work)} style={button}>打开验收</button>:null}</div></article>)}</div>}
 {preview?<section aria-label="派发预览" style={{marginTop:18,padding:18,background:"var(--paper)",borderRadius:12}}><div style={{display:"flex",justifyContent:"space-between"}}><div><h2 style={{margin:0,fontSize:16}}>派发预览 · {preview.workItemSnapshot.title}</h2><p style={{color:"var(--muted)"}}>{preview.recommendationReason}</p></div><button onClick={()=>setPreview(null)}>关闭</button></div><div style={{display:"grid",gap:8}}>{preview.candidates.map((c)=><div key={c.employeeId} style={{display:"grid",gridTemplateColumns:"1fr 1fr 100px 2fr",padding:10,background:"var(--paper-soft)",borderRadius:8}}><strong>{c.employeeName}</strong><span>{c.positionName} · 负载 {c.workload.active}/{c.workload.capacity}</span><Tag variant={c.eligible?"success":"error"}>{c.eligible?"可选择":"不可选择"}</Tag><span>{c.eligible?c.reasons.join("；"):c.ineligibleReasons.join("；")}</span></div>)}</div><button disabled={busy||!preview.selectedEmployeeId} onClick={()=>void confirm()} style={{...button,marginTop:12}}>确认派发推荐员工</button></section>:null}
 {review?<section aria-label="回执验收" style={{marginTop:18,padding:18,background:"var(--paper)",borderRadius:12}}><h2 style={{marginTop:0}}>回执与人工验收</h2><p><b>执行摘要：</b>{review.receipt.summary}</p><p><b>交付物：</b>{review.receipt.deliverables.map((d)=>d.label).join("、")}</p><p><b>验收标准：</b>{review.work.acceptanceCriteriaSnapshot.join("；")}</p><div style={{display:"flex",gap:10}}><button disabled={busy} onClick={()=>void decide("accepted")} style={button}>验收通过</button><button disabled={busy} onClick={()=>void decide("rework")} style={{...button,background:"var(--amber)"}}>要求返工</button><button onClick={()=>setReview(null)}>关闭</button></div></section>:null}
 </div>;
}
