import { useCallback, useEffect, useState } from "react";
import { get, post } from "@/api/client";
import { ConfirmDialog } from "@/components/ui/ConfirmDialog";
import { EmptyState } from "@/components/ui/EmptyState";
import { Tag } from "@/components/ui/StatusTag";

type Backup={fileName:string;size:number;createdAt:string;reason:string;integrity:"ok"|"invalid"};
type Diagnostics={database:{path:string;size:number;integrity:string;schemaVersions:number[]};counts:Record<string,number>;backups:number;security:{rawSessionKeys:number;auditSensitiveMatches:number;hostRestricted:boolean;originRestricted:boolean;credentialsInDatabase:boolean;passed:boolean};checkedAt:string};
type Audit={id:string;action:string;summary:string;targetType:string;targetId:string;createdAt:string};
type MigrationStatus={candidates:string[];imports:Array<{id:string;source_path:string;source_version:number;imported_at:string}>};
type MigrationReport={sourcePath:string;sourceHash:string;sourceVersion:number;counts:Record<string,number>;importable:Record<string,number>;skipped:Record<string,number>;ambiguities:Array<{type:string;message:string}>;sensitiveFields:string[];sourceUnchanged:boolean;imported?:Record<string,number>};
const card:React.CSSProperties={background:"var(--paper)",border:"1px solid var(--line)",borderRadius:10,padding:18};
const primary:React.CSSProperties={padding:"8px 14px",borderRadius:7,background:"var(--green)",color:"white",fontWeight:600};
const secondary:React.CSSProperties={padding:"7px 12px",borderRadius:7,border:"1px solid var(--line)",background:"var(--paper-soft)"};
const formatBytes=(value:number)=>value<1024?`${value} B`:value<1024*1024?`${(value/1024).toFixed(1)} KB`:`${(value/1024/1024).toFixed(1)} MB`;

export function SystemPanel(){const [diagnostics,setDiagnostics]=useState<Diagnostics|null>(null);const load=useCallback(async()=>setDiagnostics((await get<Diagnostics>("/system/diagnostics")).data),[]);useEffect(()=>{void load();},[load]);return <div role="tabpanel" aria-label="系统" style={{display:"grid",gap:14}}><section style={card}><h2 style={{marginTop:0}}>本地系统状态</h2>{diagnostics?<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}><Metric label="数据库" value={diagnostics.database.integrity==="ok"?"完整":"异常"}/><Metric label="Schema" value={`v${Math.max(...diagnostics.database.schemaVersions)}`}/><Metric label="数据库大小" value={formatBytes(diagnostics.database.size)}/><Metric label="最近检查" value={new Date(diagnostics.checkedAt).toLocaleTimeString("zh-CN")}/></div>:<p>正在检查…</p>}<button style={{...secondary,marginTop:14}} onClick={()=>void load()}>重新诊断</button></section></div>}

export function DataPanel(){const [status,setStatus]=useState<MigrationStatus|null>(null);const [report,setReport]=useState<MigrationReport|null>(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const load=useCallback(async()=>setStatus((await get<MigrationStatus>("/migration/legacy")).data),[]);useEffect(()=>{void load();},[load]);const dryRun=async()=>{setBusy(true);try{const result=await post<MigrationReport>("/migration/legacy/dry-run",{});setReport(result.data);setMessage("Dry-run 完成，旧文件未被修改");}catch(e){setMessage(e instanceof Error?e.message:"Dry-run 失败");}finally{setBusy(false);}};const confirm=async()=>{if(!report)return;setBusy(true);try{const result=await post<MigrationReport>("/migration/legacy/confirm",{sourcePath:report.sourcePath,sourceHash:report.sourceHash,confirm:true});setReport(result.data);setMessage("可安全映射的数据已导入；歧义项保持跳过");await load();}catch(e){setMessage(e instanceof Error?e.message:"迁移失败");}finally{setBusy(false);}};return <div role="tabpanel" aria-label="数据" style={{display:"grid",gap:14}}><section style={card}><div style={{display:"flex",justifyContent:"space-between"}}><div><h2 style={{marginTop:0}}>旧版 v9 数据迁移</h2><p style={{color:"var(--muted)"}}>先生成数量、歧义和敏感字段报告；未经确认不会写入 SQLite，也不会修改旧文件。</p></div><button disabled={busy||!status?.candidates.length} onClick={()=>void dryRun()} style={primary}>执行 Dry-run</button></div>{!status?.candidates.length?<EmptyState title="未发现旧版数据" description="应用会检查同一用户数据目录中的 nomos-data.json。"/>:<p>发现：{status.candidates.join("、")}</p>}{message?<p role="status">{message}</p>:null}{report?<div style={{padding:14,background:"var(--paper-soft)",borderRadius:8}}><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Tag variant="info">源版本 v{report.sourceVersion}</Tag><Tag variant={report.sourceUnchanged?"success":"error"}>源文件未修改</Tag><Tag variant={report.sensitiveFields.length?"warning":"success"}>敏感字段 {report.sensitiveFields.length}</Tag><Tag variant={report.ambiguities.length?"warning":"success"}>歧义 {report.ambiguities.length}</Tag></div><p>可导入：{Object.entries(report.importable).map(([k,v])=>`${k} ${v}`).join("；")}</p><p>跳过：{Object.entries(report.skipped).map(([k,v])=>`${k} ${v}`).join("；")}</p>{report.ambiguities.map((a)=><p key={`${a.type}-${a.message}`} style={{color:"var(--amber)"}}>• {a.message}</p>)}{!report.imported?<button disabled={busy} onClick={()=>void confirm()} style={primary}>确认导入可安全映射项</button>:<Tag variant="success">迁移已记录</Tag>}</div>:null}</section><section style={card}><h2 style={{marginTop:0}}>迁移历史</h2>{status?.imports.length?status.imports.map((item)=><p key={item.id}>{new Date(item.imported_at).toLocaleString("zh-CN")} · v{item.source_version} · {item.source_path}</p>):<p style={{color:"var(--muted)"}}>暂无迁移记录</p>}</section></div>}

export function BackupPanel(){const [backups,setBackups]=useState<Backup[]>([]);const [target,setTarget]=useState<Backup|null>(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const load=useCallback(async()=>setBackups((await get<Backup[]>("/system/backups")).data),[]);useEffect(()=>{void load();},[load]);const create=async()=>{setBusy(true);try{await post<Backup>("/system/backups",{confirm:true,reason:"manual-ui"});await load();setMessage("SQLite 备份已创建并通过完整性检查");}catch(e){setMessage(e instanceof Error?e.message:"备份失败");}finally{setBusy(false);}};const restore=async()=>{if(!target)return;setBusy(true);try{await post(`/system/backups/${encodeURIComponent(target.fileName)}/restore`,{confirm:true});setMessage("恢复完成；系统已自动创建恢复前保护快照");setTarget(null);await load();}catch(e){setMessage(e instanceof Error?e.message:"恢复失败");}finally{setBusy(false);}};return <div role="tabpanel" aria-label="备份"><section style={card}><div style={{display:"flex",justifyContent:"space-between"}}><div><h2 style={{marginTop:0}}>本地 SQLite 备份</h2><p style={{color:"var(--muted)"}}>备份创建后自动执行完整性检查；恢复前会再次生成保护快照。</p></div><button disabled={busy} onClick={()=>void create()} style={primary}>创建备份</button></div>{message?<p role="status">{message}</p>:null}{backups.length?<div style={{display:"grid",gap:8}}>{backups.map((b)=><div key={b.fileName} style={{display:"grid",gridTemplateColumns:"2fr 120px 170px 100px",alignItems:"center",padding:10,background:"var(--paper-soft)",borderRadius:8}}><div><strong>{b.fileName}</strong><div style={{fontSize:12,color:"var(--muted)"}}>{b.reason}</div></div><span>{formatBytes(b.size)}</span><span>{new Date(b.createdAt).toLocaleString("zh-CN")}</span><button onClick={()=>setTarget(b)} style={{color:"var(--red)"}}>恢复</button></div>)}</div>:<EmptyState title="尚无备份" description="建议在导入旧数据或重大操作前创建备份。"/>}</section><ConfirmDialog open={target!==null} title="恢复 SQLite 备份" description="当前数据库会先创建保护快照，然后替换为所选备份。运行中的执行会阻止恢复。" targetLabel={target?.fileName} confirmLabel="确认恢复" confirmVariant="danger" loading={busy} onCancel={()=>setTarget(null)} onConfirm={()=>void restore()}/></div>}

export function SecurityPanel(){const [diagnostics,setDiagnostics]=useState<Diagnostics|null>(null);const [audits,setAudits]=useState<Audit[]>([]);const load=useCallback(async()=>{const[d,a]=await Promise.all([get<Diagnostics>("/system/diagnostics"),get<Audit[]>("/system/audits")]);setDiagnostics(d.data);setAudits(a.data);},[]);useEffect(()=>{void load();},[load]);return <div role="tabpanel" aria-label="安全" style={{display:"grid",gap:14}}><section style={card}><div style={{display:"flex",justifyContent:"space-between"}}><div><h2 style={{marginTop:0}}>安全门禁</h2><p style={{color:"var(--muted)"}}>扫描数据库会话密钥、审计敏感字段和本机访问边界。</p></div>{diagnostics?<Tag variant={diagnostics.security.passed?"success":"error"}>{diagnostics.security.passed?"检查通过":"需要处理"}</Tag>:null}</div>{diagnostics?<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10}}><Metric label="原始会话密钥" value={String(diagnostics.security.rawSessionKeys)}/><Metric label="审计敏感匹配" value={String(diagnostics.security.auditSensitiveMatches)}/><Metric label="Host 限制" value={diagnostics.security.hostRestricted?"启用":"关闭"}/><Metric label="Origin 限制" value={diagnostics.security.originRestricted?"启用":"关闭"}/></div>:<p>扫描中…</p>}</section><section style={card}><h2 style={{marginTop:0}}>最近审计</h2><div style={{maxHeight:330,overflow:"auto"}}>{audits.slice(0,50).map((a)=><div key={a.id} style={{display:"grid",gridTemplateColumns:"170px 1fr 180px",padding:"8px 0",borderBottom:"1px solid var(--line)"}}><span>{new Date(a.createdAt).toLocaleString("zh-CN")}</span><span>{a.summary}</span><code>{a.action}</code></div>)}</div></section></div>}

export function AppearancePanel(){const[density,setDensity]=useState(()=>localStorage.getItem("nomos-density")||"comfortable");const choose=(value:string)=>{setDensity(value);localStorage.setItem("nomos-density",value);document.documentElement.dataset.density=value;};return <div role="tabpanel" aria-label="外观"><section style={card}><h2 style={{marginTop:0}}>界面密度</h2><div style={{display:"flex",gap:10}}>{[["comfortable","舒适"],["compact","紧凑"]].map(([value,label])=><button key={value} onClick={()=>choose(value)} style={density===value?primary:secondary}>{label}</button>)}</div><p style={{color:"var(--muted)"}}>外观偏好仅保存在本机，不进入业务数据或备份。</p></section></div>}

function Metric({label,value}:{label:string;value:string}){return <div style={{padding:12,background:"var(--paper-soft)",borderRadius:8}}><div style={{fontSize:12,color:"var(--muted)"}}>{label}</div><strong style={{display:"block",marginTop:5}}>{value}</strong></div>}
