import { useCallback, useEffect, useMemo, useState } from "react";
import { get, post } from "@/api/client";
import { EmptyState } from "@/components/ui/EmptyState";
import { StatusTag, Tag } from "@/components/ui/StatusTag";
import type { EmployeeDto, FlowDefinitionDto, ProjectDto, ProjectRuntimeDto } from "@/types/api";
const field: React.CSSProperties = { width: "100%", padding: "8px 10px", border: "1px solid var(--line-strong)", borderRadius: 8, background: "white" };
const button: React.CSSProperties = { padding: "8px 14px", borderRadius: 8, background: "var(--green)", color: "white", fontWeight: 600 };

export function ProjectPage() {
  const [projects,setProjects]=useState<ProjectDto[]>([]); const [flows,setFlows]=useState<FlowDefinitionDto[]>([]); const [employees,setEmployees]=useState<EmployeeDto[]>([]); const [runtime,setRuntime]=useState<ProjectRuntimeDto|null>(null);
  const [name,setName]=useState(""); const [goal,setGoal]=useState(""); const [owner,setOwner]=useState(""); const [flowVersion,setFlowVersion]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const [p,f,e]=await Promise.all([get<ProjectDto[]>("/projects"),get<FlowDefinitionDto[]>("/flows"),get<EmployeeDto[]>("/employees")]);setProjects(p.data);setFlows(f.data);setEmployees(e.data);},[]);
  useEffect(()=>{void load().catch((e:Error)=>setMessage(e.message));},[load]);
  const versions=useMemo(()=>flows.flatMap((f)=>f.versions.filter((v)=>v.status==="published").map((v)=>({flowName:f.name,version:v}))),[flows]); const owners=useMemo(()=>employees.filter((e)=>e.schedulable),[employees]);
  const create=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);try{await post<ProjectDto>("/projects",{name,goal,ownerEmployeeId:owner,flowVersionId:flowVersion});setName("");setGoal("");await load();setMessage("项目草稿已创建，可以启动流程快照");}catch(e){setMessage(e instanceof Error?e.message:"创建失败");}finally{setBusy(false);}};
  const start=async(project:ProjectDto)=>{setBusy(true);try{await post(`/projects/${project.id}/start`,{});await load();const data=await get<ProjectRuntimeDto>(`/projects/${project.id}/runtime`);setRuntime(data.data);setMessage("项目已启动，流程和工作项快照生成完成");}catch(e){setMessage(e instanceof Error?e.message:"启动失败");}finally{setBusy(false);}};
  const inspect=async(id:string)=>{try{setRuntime((await get<ProjectRuntimeDto>(`/projects/${id}/runtime`)).data);}catch(e){setMessage(e instanceof Error?e.message:"加载失败");}};
  return <div style={{padding:"28px 32px",overflow:"auto",height:"100%"}}><div style={{display:"flex",justifyContent:"space-between"}}><div><h1 style={{margin:0,fontSize:20}}>项目</h1><p style={{color:"var(--muted)"}}>项目启动时冻结流程版本，并按每个岗位槽位生成独立工作项。</p></div><Tag variant="success">V0.0.3 · FE-401</Tag></div>
    {message?<p role="status" style={{padding:10,background:"var(--green-soft)",borderRadius:8}}>{message}</p>:null}
    <form onSubmit={create} style={{display:"grid",gridTemplateColumns:"1.2fr 2fr 1fr 1.2fr auto",gap:10,padding:16,background:"var(--paper)",borderRadius:12}}><label>项目名称<input aria-label="项目名称" required minLength={2} value={name} onChange={(e)=>setName(e.target.value)} style={field}/></label><label>项目目标<input aria-label="项目目标" required minLength={4} value={goal} onChange={(e)=>setGoal(e.target.value)} style={field}/></label><label>项目 Owner<select aria-label="项目 Owner" required value={owner} onChange={(e)=>setOwner(e.target.value)} style={field}><option value="">请选择</option>{owners.map((e)=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>流程版本<select aria-label="流程版本" required value={flowVersion} onChange={(e)=>setFlowVersion(e.target.value)} style={field}><option value="">请选择</option>{versions.map(({flowName,version})=><option key={version.id} value={version.id}>{flowName} · {version.versionLabel}</option>)}</select></label><button disabled={busy} style={{...button,alignSelf:"end"}}>创建项目</button></form>
    {projects.length===0?<EmptyState title="尚无项目" description="先发布流程版本，再创建项目。"/>:<div style={{display:"grid",gap:10,marginTop:18}}>{projects.map((p)=><article key={p.id} style={{display:"grid",gridTemplateColumns:"1.4fr 2fr 100px auto",gap:12,alignItems:"center",padding:16,background:"var(--paper)",borderRadius:12}}><strong>{p.name}</strong><span>{p.goal}</span><Tag variant={p.status==="active"?"success":"draft"}>{p.status==="active"?"运行中":"草稿"}</Tag><div style={{display:"flex",gap:10}}>{p.status==="draft"?<button disabled={busy} onClick={()=>void start(p)} style={button}>启动</button>:null}<button onClick={()=>void inspect(p.id)} style={{color:"var(--green)"}}>查看运行</button></div></article>)}</div>}
    {runtime?<section aria-label="项目运行快照" style={{marginTop:18,padding:18,background:"var(--paper)",borderRadius:12}}><div style={{display:"flex",justifyContent:"space-between"}}><div><h2 style={{margin:0,fontSize:16}}>{runtime.project.name} · 运行快照</h2><p style={{color:"var(--muted)"}}>流程版本 {runtime.flowSnapshot?.versionLabel}，{runtime.nodeInstances.length} 个节点，{runtime.workItems.length} 个工作项</p></div><button onClick={()=>setRuntime(null)}>关闭</button></div><div style={{display:"grid",gap:8}}>{runtime.workItems.map((item)=><div key={item.id} style={{display:"grid",gridTemplateColumns:"2fr 1fr 100px",padding:10,background:"var(--paper-soft)",borderRadius:8}}><span>{item.title}</span><span>依赖 {item.dependencyIds.length} 项</span><StatusTag type="workitem" status={item.status}/></div>)}</div></section>:null}
  </div>;
}
