import { useCallback, useEffect, useMemo, useState } from "react";
import { get, post } from "@/api/client";
import { EmptyState } from "@/components/ui/EmptyState";
import { StatusTag, Tag } from "@/components/ui/StatusTag";
import type { ConnectionProfileDto, EmployeeDto, PositionDto, SkillDto } from "@/types/api";

type Tab = "employees" | "positions" | "factory";
const btn: React.CSSProperties = { padding: "8px 14px", borderRadius: 8, background: "var(--green)", color: "white", fontWeight: 600 };
const field: React.CSSProperties = { padding: "8px 10px", border: "1px solid var(--line-strong)", borderRadius: 8, background: "white", width: "100%" };

export function OrganizationPage() {
  const [tab, setTab] = useState<Tab>("employees"); const [employees, setEmployees] = useState<EmployeeDto[]>([]); const [positions, setPositions] = useState<PositionDto[]>([]);
  const [skills, setSkills] = useState<SkillDto[]>([]); const [connections, setConnections] = useState<ConnectionProfileDto[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [positionName, setPositionName] = useState(""); const [family, setFamily] = useState("研发"); const [responsibility, setResponsibility] = useState(""); const [criterion, setCriterion] = useState(""); const [skillId, setSkillId] = useState("");
  const [employeeName, setEmployeeName] = useState(""); const [employeePosition, setEmployeePosition] = useState(""); const [employeeConnection, setEmployeeConnection] = useState("");
  const load = useCallback(async () => { const [e,p,s,c] = await Promise.all([get<EmployeeDto[]>("/employees"), get<PositionDto[]>("/positions"), get<SkillDto[]>("/skills"), get<ConnectionProfileDto[]>("/connection-profiles")]); setEmployees(e.data); setPositions(p.data); setSkills(s.data); setConnections(c.data); }, []);
  useEffect(() => { void load().catch((e: Error) => setMessage(e.message)); }, [load]);
  const activePositions = useMemo(() => positions.filter((p) => p.status === "active"), [positions]); const readyConnections = useMemo(() => connections.filter((c) => c.status === "connected" && c.manageable), [connections]);
  const createPosition = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { await post<PositionDto>("/positions", { name: positionName, family, responsibilities: [responsibility], acceptanceCriteria: [criterion], skillIds: skillId ? [skillId] : [], managementPermission: { dataScopes: ["project"], visibility: ["assigned"], actions: ["read", "write"], responsibilityBoundary: "仅限所分配项目与工作项", approvalPolicy: "owner" } }); setPositionName(""); setResponsibility(""); setCriterion(""); await load(); setMessage("岗位已创建"); } catch(e) { setMessage(e instanceof Error ? e.message : "创建失败"); } finally { setBusy(false); } };
  const createEmployee = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { const created = await post<EmployeeDto>("/employees", { name: employeeName, type: "silicon", primaryPositionId: employeePosition, additionalPositionIds: [], connectionProfileId: employeeConnection }); const materialized = await post<EmployeeDto>(`/employees/${created.data.id}/materialize`, {}); const checked = await post<{ employee: EmployeeDto; passed: boolean }>(`/employees/${materialized.data.id}/onboarding-check`, {}); await load(); setEmployeeName(""); setMessage(checked.data.passed ? "数字员工已通过入职检查，可参与调度" : "员工已创建，但入职检查未通过"); setTab("employees"); } catch(e) { setMessage(e instanceof Error ? e.message : "创建失败"); } finally { setBusy(false); } };
  const lifecycle = async (employee: EmployeeDto, action: "suspend" | "resume") => { setBusy(true); try { await post<EmployeeDto>(`/employees/${employee.id}/${action}`, { version: employee.version }); await load(); setMessage(action === "suspend" ? "员工已暂停" : "员工已恢复调度"); } catch(e) { setMessage(e instanceof Error ? e.message : "操作失败"); } finally { setBusy(false); } };
  return <div style={{ padding: "28px 32px", overflow: "auto", height: "100%" }}>
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "start" }}><div><h1 style={{ margin: 0, fontSize: 20 }}>组织</h1><p style={{ color: "var(--muted)" }}>岗位定义工作责任，员工是可调度主体；技术连接本身不是员工。</p></div><Tag variant="success">V0.0.3 · FE-202~204</Tag></div>
    <nav aria-label="组织分类" style={{ display: "flex", gap: 6, borderBottom: "1px solid var(--line)", marginBottom: 18 }}>{([["employees","员工名录"],["positions","岗位"],["factory","数字员工工厂"]] as const).map(([key,label]) => <button role="tab" aria-selected={tab===key} key={key} onClick={() => setTab(key)} style={{ padding: "10px 14px", color: tab===key ? "var(--green)" : "var(--muted)", borderBottom: tab===key ? "2px solid var(--green)" : "2px solid transparent" }}>{label}</button>)}</nav>
    {message && <p role="status" style={{ padding: 10, borderRadius: 8, background: "var(--green-soft)" }}>{message}</p>}
    {tab === "employees" && (employees.length === 0 ? <EmptyState title="尚无员工" description="前往数字员工工厂，以已连接的智能体创建首位员工。" action={<button style={btn} onClick={() => setTab("factory")}>创建数字员工</button>} /> : <div style={{ display: "grid", gap: 10 }}>{employees.map((e) => <article key={e.id} style={{ display: "grid", gridTemplateColumns: "2fr 1fr 1fr 1fr auto", alignItems: "center", gap: 12, padding: 16, borderRadius: 12, background: "var(--paper)" }}><div><strong>{e.name}</strong><div style={{ color: "var(--muted)", fontSize: 12 }}>{e.employeeNo} · {e.type === "silicon" ? "硅基" : "碳基"}</div></div><span>{positions.find((p) => p.id === e.primaryPositionId)?.name || "未设岗位"}</span><StatusTag type="employee" status={e.status}/><span>{e.runtimeBinding?.sessionKeyMasked || "未物化会话"}</span><button disabled={busy} onClick={() => void lifecycle(e, e.status === "suspended" ? "resume" : "suspend")} style={{ color: "var(--green)" }}>{e.status === "suspended" ? "恢复" : "暂停"}</button></article>)}</div>)}
    {tab === "positions" && <div style={{ display: "grid", gridTemplateColumns: "minmax(320px, 0.8fr) 1.2fr", gap: 18 }}><form onSubmit={createPosition} style={{ background: "var(--paper)", padding: 18, borderRadius: 12, display: "grid", gap: 12, alignSelf: "start" }}><h2 style={{ margin: 0, fontSize: 16 }}>创建岗位</h2><label>岗位名称<input required minLength={2} value={positionName} onChange={(e) => setPositionName(e.target.value)} style={field}/></label><label>岗位族<input required value={family} onChange={(e) => setFamily(e.target.value)} style={field}/></label><label>核心职责<textarea required value={responsibility} onChange={(e) => setResponsibility(e.target.value)} style={field}/></label><label>验收标准<textarea required value={criterion} onChange={(e) => setCriterion(e.target.value)} style={field}/></label><label>关联 Skill<select value={skillId} onChange={(e) => setSkillId(e.target.value)} style={field}><option value="">暂不关联</option>{skills.filter((s) => s.status === "active").map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button disabled={busy} style={btn}>创建岗位</button></form><div style={{ display: "grid", gap: 10 }}>{positions.length === 0 ? <EmptyState title="尚无岗位" /> : positions.map((p) => <article key={p.id} style={{ background: "var(--paper)", padding: 16, borderRadius: 12 }}><div style={{ display: "flex", justifyContent: "space-between" }}><strong>{p.name}</strong><Tag variant={p.status === "active" ? "success" : "neutral"}>{p.family}</Tag></div><p>{p.responsibilities.join("；")}</p><small style={{ color: "var(--muted)" }}>验收：{p.acceptanceCriteria.join("；")} · Skill {p.skillIds.length} 项 · 员工 {p.referenceSummary.employees} 位</small></article>)}</div></div>}
    {tab === "factory" && <form onSubmit={createEmployee} style={{ maxWidth: 680, background: "var(--paper)", padding: 22, borderRadius: 12, display: "grid", gap: 14 }}><div><h2 style={{ margin: 0 }}>数字员工四步向导</h2><p style={{ color: "var(--muted)" }}>身份 → 岗位 → 技术连接 → 独立会话与入职检查</p></div><label>员工名称<input aria-label="员工名称" required minLength={2} value={employeeName} onChange={(e) => setEmployeeName(e.target.value)} style={field}/></label><label>主岗位<select aria-label="主岗位" required value={employeePosition} onChange={(e) => setEmployeePosition(e.target.value)} style={field}><option value="">请选择</option>{activePositions.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>技术连接<select aria-label="技术连接" required value={employeeConnection} onChange={(e) => setEmployeeConnection(e.target.value)} style={field}><option value="">请选择已连接实例</option>{readyConnections.map((c) => <option key={c.id} value={c.id}>{c.name} · 容量 {c.activeSessions}/{c.concurrencyCapacity}</option>)}</select></label>{activePositions.length === 0 && <p style={{ color: "var(--amber)" }}>请先创建启用中的岗位。</p>}{readyConnections.length === 0 && <p style={{ color: "var(--amber)" }}>请先在设置中保存并检查一个可管理连接。</p>}<button disabled={busy || !employeePosition || !employeeConnection} style={btn}>{busy ? "正在物化并检查…" : "创建并完成入职检查"}</button></form>}
  </div>;
}
