import { randomUUID } from "node:crypto";
import type { NomosHandler } from "../middleware/core";
import { createDtoValidator } from "../middleware/schema";
import { sendSuccess } from "../response";
import type { DbConnection } from "../../infrastructure/database/connection";
import type { TransactionManager } from "../../infrastructure/database/transaction";
import { AuditLogger } from "../../infrastructure/audit/audit";
import { ErrorCodes, NomosError, notFound, validationError, versionConflict } from "../../domain/shared/errors";
import { createEmployee, createPosition, createSkill, mapEmployee, mapPosition, mapSkill, materializeEmployee, onboardingCheck, transitionEmployee, updatePosition, updateSkill } from "../../application/organization/service";

type Dict = Record<string, unknown>;
const skillCreate = createDtoValidator<Dict>({ name: { type: "string", minLength: 2, maxLength: 80 }, category: { type: "string", enum: ["general", "domain", "position_specific"] }, level: { type: "number", integer: true, min: 0, max: 4 }, source: { type: "string", enum: ["manual", "retrospective", "imported"], default: "manual", optional: true } });
const skillUpdate = createDtoValidator<Dict>({ name: { type: "string", minLength: 2, maxLength: 80, optional: true }, category: { type: "string", enum: ["general", "domain", "position_specific"], optional: true }, level: { type: "number", integer: true, min: 0, max: 4, optional: true }, status: { type: "string", enum: ["active", "inactive"], optional: true }, version: { type: "number", integer: true, min: 1 } });
const permissionSchema = { type: "object" as const, properties: { dataScopes: { type: "array" as const }, visibility: { type: "array" as const }, actions: { type: "array" as const }, responsibilityBoundary: { type: "string" as const, minLength: 1, maxLength: 500 }, approvalPolicy: { type: "string" as const, enum: ["none", "owner"] } } };
const positionCreate = createDtoValidator<Dict>({ name: { type: "string", minLength: 2, maxLength: 80 }, family: { type: "string", minLength: 2, maxLength: 80 }, responsibilities: { type: "array", minLength: 1 }, acceptanceCriteria: { type: "array", minLength: 1 }, skillIds: { type: "array", default: [], optional: true }, managementPermission: permissionSchema });
const positionUpdate = createDtoValidator<Dict>({ name: { type: "string", minLength: 2, maxLength: 80, optional: true }, family: { type: "string", minLength: 2, maxLength: 80, optional: true }, responsibilities: { type: "array", minLength: 1, optional: true }, acceptanceCriteria: { type: "array", minLength: 1, optional: true }, skillIds: { type: "array", optional: true }, managementPermission: { ...permissionSchema, optional: true }, status: { type: "string", enum: ["active", "inactive"], optional: true }, version: { type: "number", integer: true, min: 1 } });
const employeeCreate = createDtoValidator<Dict>({ name: { type: "string", minLength: 2, maxLength: 80 }, type: { type: "string", enum: ["carbon", "silicon", "hybrid"] }, primaryPositionId: { type: "string", minLength: 1, optional: true }, additionalPositionIds: { type: "array", default: [], optional: true }, connectionProfileId: { type: "string", minLength: 1, optional: true } });
const lifecycle = createDtoValidator<Dict>({ version: { type: "number", integer: true, min: 1 }, confirm: { type: "boolean", default: true, optional: true } });
const permissionCreate = createDtoValidator<Dict>({ employeeId: { type: "string", minLength: 1 }, targetPositionId: { type: "string", minLength: 1 }, requestedScopes: { type: "array", minLength: 1 }, reason: { type: "string", minLength: 4, maxLength: 500 }, expiresAt: { type: "string", minLength: 20, maxLength: 40 } });
const permissionAction = createDtoValidator<Dict>({ version: { type: "number", integer: true, min: 1 }, reviewerEmployeeId: { type: "string", minLength: 1, optional: true }, reason: { type: "string", minLength: 2, maxLength: 500, optional: true } });

function valid(result: ReturnType<typeof skillCreate>, requestId: string): Dict {
  if (!result.success || !result.data) throw validationError("请求字段不符合合同", requestId, result.errors);
  return result.data;
}
function row(db: DbConnection, table: string, id: string, requestId: string) {
  const found = db.get<Record<string, unknown>>(`SELECT * FROM ${table} WHERE id = ?`, id);
  if (!found) throw notFound(`${table}/${id}`, requestId); return found;
}
function audit(session: Parameters<TransactionManager["run"]>[0] extends (s: infer S) => unknown ? S : never, ctx: { requestId: string }, action: string, summary: string, targetType: string, targetId: string) {
  new AuditLogger(session).append({ action, summary, actor: { type: "user", id: null, name: "本机 Owner" }, targetType, targetId, requestId: ctx.requestId });
}

export function organizationRouter(db: DbConnection, tx: TransactionManager) {
  const listSkills: NomosHandler = (_req, res, ctx) => sendSuccess(res, 200, db.all<Record<string, unknown>>("SELECT * FROM skills ORDER BY updated_at DESC").map((r) => mapSkill(db, r)), ctx.requestId);
  const addSkill: NomosHandler = async (_req, res, ctx) => { const input = valid(skillCreate(ctx.body), ctx.requestId); const id = await tx.run((s) => { const created = createSkill(s, input as never, ctx.requestId); audit(s, ctx, "skill.created", `创建 Skill ${input.name}`, "skill", created); return created; }); sendSuccess(res, 201, mapSkill(db, row(db, "skills", id, ctx.requestId)), ctx.requestId); };
  const editSkill: NomosHandler = async (_req, res, ctx) => { const input = valid(skillUpdate(ctx.body), ctx.requestId); await tx.run((s) => { updateSkill(s, ctx.params.id, input as never, ctx.requestId); audit(s, ctx, "skill.updated", "更新 Skill", "skill", ctx.params.id); }); sendSuccess(res, 200, mapSkill(db, row(db, "skills", ctx.params.id, ctx.requestId)), ctx.requestId); };

  const listPositions: NomosHandler = (_req, res, ctx) => sendSuccess(res, 200, db.all<Record<string, unknown>>("SELECT * FROM positions ORDER BY updated_at DESC").map((r) => mapPosition(db, r)), ctx.requestId);
  const getPosition: NomosHandler = (_req, res, ctx) => sendSuccess(res, 200, mapPosition(db, row(db, "positions", ctx.params.id, ctx.requestId)), ctx.requestId);
  const addPosition: NomosHandler = async (_req, res, ctx) => { const input = valid(positionCreate(ctx.body), ctx.requestId); const id = await tx.run((s) => { const created = createPosition(s, input as never, ctx.requestId); audit(s, ctx, "position.created", `创建岗位 ${input.name}`, "position", created); return created; }); sendSuccess(res, 201, mapPosition(db, row(db, "positions", id, ctx.requestId)), ctx.requestId); };
  const editPosition: NomosHandler = async (_req, res, ctx) => { const input = valid(positionUpdate(ctx.body), ctx.requestId); await tx.run((s) => { updatePosition(s, ctx.params.id, input as never, ctx.requestId); audit(s, ctx, "position.updated", "更新岗位", "position", ctx.params.id); }); sendSuccess(res, 200, mapPosition(db, row(db, "positions", ctx.params.id, ctx.requestId)), ctx.requestId); };

  const listEmployees: NomosHandler = (_req, res, ctx) => sendSuccess(res, 200, db.all<Record<string, unknown>>("SELECT * FROM employees ORDER BY updated_at DESC").map((r) => mapEmployee(db, r)), ctx.requestId);
  const getEmployee: NomosHandler = (_req, res, ctx) => sendSuccess(res, 200, mapEmployee(db, row(db, "employees", ctx.params.id, ctx.requestId)), ctx.requestId);
  const addEmployee: NomosHandler = async (_req, res, ctx) => { const input = valid(employeeCreate(ctx.body), ctx.requestId); const id = await tx.run((s) => { const created = createEmployee(s, input as never, ctx.requestId); audit(s, ctx, "employee.created", `创建员工草稿 ${input.name}`, "employee", created); return created; }); sendSuccess(res, 201, mapEmployee(db, row(db, "employees", id, ctx.requestId)), ctx.requestId); };
  const materialize: NomosHandler = async (_req, res, ctx) => { await tx.run((s) => { materializeEmployee(s, ctx.params.id, ctx.requestId); audit(s, ctx, "employee.materialized", "物化独立会话与岗位提示词", "employee", ctx.params.id); }); sendSuccess(res, 200, mapEmployee(db, row(db, "employees", ctx.params.id, ctx.requestId)), ctx.requestId); };
  const checkOnboarding: NomosHandler = async (_req, res, ctx) => { const passed = await tx.run((s) => { const result = onboardingCheck(s, ctx.params.id, ctx.requestId); audit(s, ctx, "employee.onboarding_checked", result ? "员工入职检查通过" : "员工入职检查失败", "employee", ctx.params.id); return result; }); sendSuccess(res, 200, { employee: mapEmployee(db, row(db, "employees", ctx.params.id, ctx.requestId)), passed }, ctx.requestId); };
  const employeeAction = (action: "suspend" | "resume" | "offboard"): NomosHandler => async (_req, res, ctx) => { const input = valid(lifecycle(ctx.body), ctx.requestId); if (action === "offboard" && input.confirm !== true) throw validationError("离职操作需要显式确认", ctx.requestId); await tx.run((s) => { transitionEmployee(s, ctx.params.id, action, Number(input.version), ctx.requestId); audit(s, ctx, `employee.${action}`, `员工生命周期动作 ${action}`, "employee", ctx.params.id); }); sendSuccess(res, 200, mapEmployee(db, row(db, "employees", ctx.params.id, ctx.requestId)), ctx.requestId); };

  const listPermissionRequests: NomosHandler = (_req, res, ctx) => { const now = new Date().toISOString(); db.prepare("UPDATE permission_requests SET status='expired',updated_at=?,version=version+1 WHERE status='approved' AND expires_at <= ?").run(now, now); const rows = db.all<Record<string, unknown>>("SELECT * FROM permission_requests ORDER BY created_at DESC").map((r) => ({ id: r.id, employeeId: r.employee_id, targetPositionId: r.target_position_id, requestedScopes: JSON.parse(String(r.requested_scopes)), reason: r.reason, status: r.status, reviewerEmployeeId: r.reviewer_employee_id, expiresAt: r.expires_at, createdAt: r.created_at, updatedAt: r.updated_at, version: r.version })); sendSuccess(res, 200, rows, ctx.requestId); };
  const addPermissionRequest: NomosHandler = async (_req, res, ctx) => { const input = valid(permissionCreate(ctx.body), ctx.requestId); const expires = new Date(String(input.expiresAt)); if (!Number.isFinite(expires.getTime()) || expires <= new Date()) throw validationError("expiresAt 必须是未来时间", ctx.requestId); const id = await tx.run((s) => { if (!s.get("SELECT id FROM employees WHERE id=?", String(input.employeeId))) throw notFound("employee", ctx.requestId); if (!s.get("SELECT id FROM positions WHERE id=?", String(input.targetPositionId))) throw notFound("position", ctx.requestId); const created = randomUUID(); const now = new Date().toISOString(); s.run("INSERT INTO permission_requests(id,employee_id,target_position_id,requested_scopes,reason,status,expires_at,created_at,updated_at,version) VALUES(?,?,?,?,?,'pending',?,?,?,1)", created, String(input.employeeId), String(input.targetPositionId), JSON.stringify(input.requestedScopes), String(input.reason), expires.toISOString(), now, now); audit(s, ctx, "permission_request.created", "提交岗位外权限申请", "permission_request", created); return created; }); sendSuccess(res, 201, { id, status: "pending" }, ctx.requestId); };
  const permissionActionHandler = (action: "approve" | "reject" | "revoke"): NomosHandler => async (_req, res, ctx) => { const input = valid(permissionAction(ctx.body), ctx.requestId); await tx.run((s) => { const current = s.get<Record<string, unknown>>("SELECT * FROM permission_requests WHERE id=?", ctx.params.id); if (!current) throw notFound("permission_request", ctx.requestId); const allowed = action === "revoke" ? current.status === "approved" : current.status === "pending"; if (!allowed) throw new NomosError({ title: "权限申请状态不允许该操作", status: 409, code: ErrorCodes.INVALID_STATE_TRANSITION, detail: `当前状态 ${current.status}`, requestId: ctx.requestId }); const status = action === "approve" ? "approved" : action === "reject" ? "rejected" : "revoked"; const result = s.run("UPDATE permission_requests SET status=?,reviewer_employee_id=?,updated_at=?,version=version+1 WHERE id=? AND version=?", status, input.reviewerEmployeeId ?? null, new Date().toISOString(), ctx.params.id, Number(input.version)); if (Number(result.changes) !== 1) throw versionConflict(ctx.requestId); audit(s, ctx, `permission_request.${action}`, `权限申请${action}`, "permission_request", ctx.params.id); }); sendSuccess(res, 200, { id: ctx.params.id, status: action === "approve" ? "approved" : action === "reject" ? "rejected" : "revoked" }, ctx.requestId); };

  return { listSkills, addSkill, editSkill, listPositions, getPosition, addPosition, editPosition, listEmployees, getEmployee, addEmployee, materialize, checkOnboarding,
    suspendEmployee: employeeAction("suspend"), resumeEmployee: employeeAction("resume"), offboardEmployee: employeeAction("offboard"), listPermissionRequests, addPermissionRequest,
    approvePermissionRequest: permissionActionHandler("approve"), rejectPermissionRequest: permissionActionHandler("reject"), revokePermissionRequest: permissionActionHandler("revoke") };
}
