import { randomUUID } from "node:crypto";
import type { NomosHandler } from "../middleware/core";
import { createDtoValidator } from "../middleware/schema";
import { sendSuccess } from "../response";
import type { DbConnection, DbSession } from "../../infrastructure/database/connection";
import type { TransactionManager } from "../../infrastructure/database/transaction";
import { AuditLogger } from "../../infrastructure/audit/audit";
import { ErrorCodes, NomosError, notFound, validationError } from "../../domain/shared/errors";

type Dict = Record<string, unknown>;
type NodeInput = { key: string; name: string; goal: string; inputs?: string[]; outputs?: string[]; positionSlots: Array<{ name: string; requiredPositionId: string; executionType?: string; routingStrategy?: string; fixedEmployeeId?: string | null }>; acceptance: { required: boolean; reviewerPositionId?: string | null; criteria: string[] }; failurePolicy?: { maxAttempts: number; reworkNodeKey?: string | null } };
type EdgeInput = { fromNodeKey: string; toNodeKey: string; condition?: string | null };

const flowCreate = createDtoValidator<Dict>({ name: { type: "string", minLength: 2, maxLength: 120 }, description: { type: "string", maxLength: 1000, optional: true } });
const versionCreate = createDtoValidator<Dict>({ versionLabel: { type: "string", minLength: 1, maxLength: 30 }, nodes: { type: "array", minLength: 1, maxLength: 50 }, edges: { type: "array", maxLength: 200, default: [], optional: true } });
const projectCreate = createDtoValidator<Dict>({ name: { type: "string", minLength: 2, maxLength: 120 }, goal: { type: "string", minLength: 4, maxLength: 2000 }, ownerEmployeeId: { type: "string", minLength: 1 }, flowVersionId: { type: "string", minLength: 1 } });
function valid(result: ReturnType<typeof flowCreate>, requestId: string) { if (!result.success || !result.data) throw validationError("请求字段不符合合同", requestId, result.errors); return result.data; }
function required<T extends Dict>(db: DbConnection | DbSession, table: string, id: string, requestId: string): T { const result = db.get<T>(`SELECT * FROM ${table} WHERE id=?`, id); if (!result) throw notFound(`${table}/${id}`, requestId); return result; }
const parse = <T>(value: unknown, fallback: T): T => { try { return JSON.parse(String(value)) as T; } catch { return fallback; } };
function audit(s: DbSession, requestId: string, action: string, summary: string, type: string, id: string) { new AuditLogger(s).append({ action, summary, actor: { type: "user", id: null, name: "本机 Owner" }, targetType: type, targetId: id, requestId }); }

function mapNode(db: DbConnection | DbSession, row: Dict) {
  const slots = db.all<Dict>("SELECT * FROM position_slots WHERE flow_node_id=? ORDER BY created_at", String(row.id)).map((s) => ({ id: s.id, name: s.name, requiredPositionId: s.required_position_id, executionType: s.execution_type, routingStrategy: s.routing_strategy, fixedEmployeeId: s.fixed_employee_id }));
  return { id: row.id, key: row.key, name: row.name, goal: row.goal || "", inputs: parse(row.inputs, []), outputs: parse(row.outputs, []), positionSlots: slots,
    acceptance: { required: Boolean(row.acceptance_required), reviewerPositionId: row.acceptance_reviewer_position_id, criteria: parse(row.acceptance_criteria, []) }, failurePolicy: parse(row.failure_policy, { maxAttempts: 1, reworkNodeKey: null }) };
}
function mapVersion(db: DbConnection | DbSession, row: Dict) {
  const nodes = db.all<Dict>("SELECT * FROM flow_nodes WHERE flow_version_id=? ORDER BY created_at", String(row.id)).map((n) => mapNode(db, n));
  const edges = db.all<Dict>("SELECT * FROM flow_edges WHERE flow_version_id=? ORDER BY created_at", String(row.id)).map((e) => ({ fromNodeId: e.from_node_id, toNodeId: e.to_node_id, condition: e.condition }));
  return { id: row.id, flowDefinitionId: row.flow_definition_id, versionLabel: row.version_label, status: row.status, nodes, edges, validation: parse(row.validation, []), publishedAt: row.published_at, createdAt: row.created_at, updatedAt: row.updated_at, version: row.version };
}
function mapWork(row: Dict) { return { id: row.id, projectId: row.project_id, nodeInstanceId: row.node_instance_id, positionSlotId: row.position_slot_id, title: row.title, requirements: row.requirements || "", requiredPositionId: row.required_position_id, assigneeEmployeeId: row.assignee_employee_id, actingPositionId: row.acting_position_id, status: row.status, attempt: row.attempt, acceptanceCriteriaSnapshot: parse(row.acceptance_criteria_snapshot, []), dependencyIds: parse(row.dependency_ids, []), createdAt: row.created_at, updatedAt: row.updated_at, version: row.version }; }

function validateGraph(db: DbConnection | DbSession, versionId: string) {
  const nodes = db.all<Dict>("SELECT * FROM flow_nodes WHERE flow_version_id=?", versionId); const edges = db.all<Dict>("SELECT * FROM flow_edges WHERE flow_version_id=?", versionId);
  const issues: Array<{ severity: "error" | "warning"; code: string; nodeId: string | null; message: string }> = []; const ids = new Set(nodes.map((n) => String(n.id)));
  for (const node of nodes) { const slots = db.all<Dict>("SELECT * FROM position_slots WHERE flow_node_id=?", String(node.id)); if (slots.length === 0) issues.push({ severity: "error", code: "POSITION_SLOT_REQUIRED", nodeId: String(node.id), message: "节点至少需要一个岗位槽位" }); if (Boolean(node.acceptance_required) && parse<unknown[]>(node.acceptance_criteria, []).length === 0) issues.push({ severity: "error", code: "ACCEPTANCE_REQUIRED", nodeId: String(node.id), message: "需要验收的节点必须定义验收标准" }); }
  const indegree = new Map([...ids].map((id) => [id, 0])); const graph = new Map([...ids].map((id) => [id, [] as string[]]));
  for (const edge of edges) { const from = String(edge.from_node_id), to = String(edge.to_node_id); if (!ids.has(from) || !ids.has(to)) issues.push({ severity: "error", code: "BROKEN_EDGE", nodeId: null, message: "边引用了不存在的节点" }); else { graph.get(from)!.push(to); indegree.set(to, (indegree.get(to) || 0) + 1); } }
  const queue = [...ids].filter((id) => indegree.get(id) === 0); let visited = 0; while (queue.length) { const id = queue.shift()!; visited++; for (const next of graph.get(id) || []) { indegree.set(next, indegree.get(next)! - 1); if (indegree.get(next) === 0) queue.push(next); } }
  if (visited !== nodes.length) issues.push({ severity: "error", code: "FLOW_CYCLE", nodeId: null, message: "流程存在环路" });
  if (nodes.length > 1) { const touched = new Set(edges.flatMap((e) => [String(e.from_node_id), String(e.to_node_id)])); for (const node of nodes) if (!touched.has(String(node.id))) issues.push({ severity: "error", code: "DISCONNECTED_NODE", nodeId: String(node.id), message: "节点未连接到流程" }); }
  return issues;
}

export function workflowRouter(db: DbConnection, tx: TransactionManager) {
  const listFlows: NomosHandler = (_req,res,ctx) => { const data = db.all<Dict>("SELECT * FROM flow_definitions ORDER BY updated_at DESC").map((f) => ({ id:f.id,name:f.name,description:f.description,status:f.status,versions:db.all<Dict>("SELECT * FROM flow_versions WHERE flow_definition_id=? ORDER BY created_at DESC",String(f.id)).map((v)=>mapVersion(db,v)),createdAt:f.created_at,updatedAt:f.updated_at,version:f.version })); sendSuccess(res,200,data,ctx.requestId); };
  const addFlow: NomosHandler = async (_req,res,ctx) => { const input=valid(flowCreate(ctx.body),ctx.requestId); const id=await tx.run((s)=>{const created=randomUUID(),now=new Date().toISOString();s.run("INSERT INTO flow_definitions(id,name,description,status,created_at,updated_at,version) VALUES(?,?,?,'draft',?,?,1)",created,input.name,String(input.description||""),now,now);audit(s,ctx.requestId,"flow.created",`创建流程 ${input.name}`,"flow",created);return created;}); sendSuccess(res,201,{id,name:input.name,status:"draft"},ctx.requestId); };
  const addVersion: NomosHandler = async (_req,res,ctx) => { const input=valid(versionCreate(ctx.body),ctx.requestId); const nodes=input.nodes as NodeInput[],edges=input.edges as EdgeInput[]; const keys=new Set<string>(); for(const n of nodes){if(!n.key||!n.name||!Array.isArray(n.positionSlots)||!n.acceptance)throw validationError("节点字段不完整",ctx.requestId);if(keys.has(n.key))throw validationError("节点 key 必须唯一",ctx.requestId);keys.add(n.key);for(const slot of n.positionSlots){const p=required<Dict>(db,"positions",slot.requiredPositionId,ctx.requestId);if(p.status!=="active")throw validationError("岗位槽位只能引用启用岗位",ctx.requestId);}} for(const e of edges)if(!keys.has(e.fromNodeKey)||!keys.has(e.toNodeKey))throw validationError("边引用了不存在的节点 key",ctx.requestId);
    const id=await tx.run((s)=>{required(s,"flow_definitions",ctx.params.id,ctx.requestId);const duplicate=s.get("SELECT id FROM flow_versions WHERE flow_definition_id=? AND version_label=?",ctx.params.id,String(input.versionLabel));if(duplicate)throw validationError("版本号已存在",ctx.requestId);const created=randomUUID(),now=new Date().toISOString();s.run("INSERT INTO flow_versions(id,flow_definition_id,version_label,status,nodes,edges,validation,created_at,updated_at,version) VALUES(?,?,?,'draft',?,?, '[]',?,?,1)",created,ctx.params.id,String(input.versionLabel),JSON.stringify(nodes),JSON.stringify(edges),now,now);const nodeIds=new Map<string,string>();for(const n of nodes){const nid=randomUUID();nodeIds.set(n.key,nid);s.run("INSERT INTO flow_nodes(id,flow_version_id,key,name,goal,inputs,outputs,acceptance_required,acceptance_reviewer_position_id,acceptance_criteria,failure_policy,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",nid,created,n.key,n.name,n.goal||"",JSON.stringify(n.inputs||[]),JSON.stringify(n.outputs||[]),n.acceptance.required?1:0,n.acceptance.reviewerPositionId||null,JSON.stringify(n.acceptance.criteria||[]),JSON.stringify(n.failurePolicy||{maxAttempts:1,reworkNodeKey:null}),now,now);for(const slot of n.positionSlots)s.run("INSERT INTO position_slots(id,flow_node_id,name,required_position_id,execution_type,routing_strategy,fixed_employee_id,created_at) VALUES(?,?,?,?,?,?,?,?)",randomUUID(),nid,slot.name,slot.requiredPositionId,slot.executionType||"silicon",slot.routingStrategy||"auto",slot.fixedEmployeeId||null,now);}for(const e of edges)s.run("INSERT INTO flow_edges(id,flow_version_id,from_node_id,to_node_id,condition,created_at) VALUES(?,?,?,?,?,?)",randomUUID(),created,nodeIds.get(e.fromNodeKey)!,nodeIds.get(e.toNodeKey)!,e.condition||null,now);audit(s,ctx.requestId,"flow_version.created",`创建流程版本 ${input.versionLabel}`,"flow_version",created);return created;}); sendSuccess(res,201,mapVersion(db,required(db,"flow_versions",id,ctx.requestId)),ctx.requestId); };
  const validateVersion: NomosHandler = async (_req,res,ctx) => { required(db,"flow_versions",ctx.params.version,ctx.requestId); const issues=validateGraph(db,ctx.params.version); db.prepare("UPDATE flow_versions SET validation=?,updated_at=?,version=version+1 WHERE id=? AND status='draft'").run(JSON.stringify(issues),new Date().toISOString(),ctx.params.version); sendSuccess(res,200,{valid:!issues.some((i)=>i.severity==="error"),issues},ctx.requestId); };
  const publishVersion: NomosHandler = async (_req,res,ctx) => { const version=required<Dict>(db,"flow_versions",ctx.params.version,ctx.requestId);if(version.status!=="draft")throw new NomosError({title:"流程版本不可修改",status:409,code:ErrorCodes.INVALID_STATE_TRANSITION,detail:"只有草稿版本可以发布",requestId:ctx.requestId});const issues=validateGraph(db,ctx.params.version);if(issues.some((i)=>i.severity==="error"))throw new NomosError({title:"流程校验失败",status:409,code:ErrorCodes.FLOW_VALIDATION_FAILED,detail:issues.map((i)=>i.message).join("；"),requestId:ctx.requestId});await tx.run((s)=>{const now=new Date().toISOString();s.run("UPDATE flow_versions SET status='published',validation=?,published_at=?,updated_at=?,version=version+1 WHERE id=?",JSON.stringify(issues),now,now,ctx.params.version);s.run("UPDATE flow_definitions SET status='published',updated_at=?,version=version+1 WHERE id=?",now,ctx.params.id);audit(s,ctx.requestId,"flow_version.published","发布不可变流程版本","flow_version",ctx.params.version);});sendSuccess(res,200,mapVersion(db,required(db,"flow_versions",ctx.params.version,ctx.requestId)),ctx.requestId); };
  const listProjects: NomosHandler = (_req,res,ctx)=>sendSuccess(res,200,db.all<Dict>("SELECT * FROM projects ORDER BY updated_at DESC").map((p)=>({id:p.id,name:p.name,goal:p.goal,ownerEmployeeId:p.owner_employee_id,flowVersionId:p.flow_version_id,status:p.status,createdAt:p.created_at,updatedAt:p.updated_at,version:p.version})),ctx.requestId);
  const addProject: NomosHandler = async (_req,res,ctx)=>{const input=valid(projectCreate(ctx.body),ctx.requestId);const owner=required<Dict>(db,"employees",String(input.ownerEmployeeId),ctx.requestId);if(owner.status!=="schedulable")throw validationError("项目 Owner 必须是可调度员工",ctx.requestId);const fv=required<Dict>(db,"flow_versions",String(input.flowVersionId),ctx.requestId);if(fv.status!=="published")throw validationError("项目只能使用已发布流程版本",ctx.requestId);const id=await tx.run((s)=>{const created=randomUUID(),now=new Date().toISOString();s.run("INSERT INTO projects(id,name,goal,owner_employee_id,flow_version_id,status,created_at,updated_at,version) VALUES(?,?,?,?,?,'draft',?,?,1)",created,input.name,input.goal,input.ownerEmployeeId,input.flowVersionId,now,now);audit(s,ctx.requestId,"project.created",`创建项目 ${input.name}`,"project",created);return created;});sendSuccess(res,201,{id,name:input.name,status:"draft"},ctx.requestId);};
  const startProject: NomosHandler = async (_req,res,ctx)=>{const project=required<Dict>(db,"projects",ctx.params.id,ctx.requestId);if(project.status!=="draft")throw new NomosError({title:"项目状态不允许启动",status:409,code:ErrorCodes.INVALID_STATE_TRANSITION,detail:`当前状态 ${project.status}`,requestId:ctx.requestId});const version=required<Dict>(db,"flow_versions",String(project.flow_version_id),ctx.requestId);if(version.status!=="published")throw validationError("流程版本未发布",ctx.requestId);await tx.run((s)=>{const now=new Date().toISOString(),instance=randomUUID();s.run("INSERT INTO flow_instances(id,project_id,flow_version_id,status,created_at,updated_at) VALUES(?,?,?,'running',?,?)",instance,project.id,version.id,now,now);const nodes=s.all<Dict>("SELECT * FROM flow_nodes WHERE flow_version_id=? ORDER BY created_at",String(version.id));const instanceByNode=new Map<string,string>(),itemsByNode=new Map<string,string[]>();for(const node of nodes){const ni=randomUUID();instanceByNode.set(String(node.id),ni);itemsByNode.set(String(node.id),[]);s.run("INSERT INTO node_instances(id,flow_instance_id,flow_node_id,status,created_at,updated_at) VALUES(?,?,?,'pending',?,?)",ni,instance,node.id,now,now);for(const slot of s.all<Dict>("SELECT * FROM position_slots WHERE flow_node_id=?",String(node.id))){const wi=randomUUID();itemsByNode.get(String(node.id))!.push(wi);s.run("INSERT INTO work_items(id,project_id,node_instance_id,position_slot_id,title,requirements,required_position_id,status,attempt,acceptance_criteria_snapshot,dependency_ids,created_at,updated_at,version) VALUES(?,?,?,?,?,?,?,'draft',1,?,'[]',?,?,1)",wi,project.id,ni,slot.id,`${node.name} · ${slot.name}`,String(node.goal||""),slot.required_position_id,node.acceptance_criteria,now,now);}}const incoming=new Set<string>();for(const edge of s.all<Dict>("SELECT * FROM flow_edges WHERE flow_version_id=?",String(version.id))){incoming.add(String(edge.to_node_id));const deps=itemsByNode.get(String(edge.from_node_id))||[];for(const wi of itemsByNode.get(String(edge.to_node_id))||[]){const old=s.get<{dependency_ids:string}>("SELECT dependency_ids FROM work_items WHERE id=?",wi);const merged=[...new Set([...parse<string[]>(old?.dependency_ids,[]),...deps])];s.run("UPDATE work_items SET dependency_ids=? WHERE id=?",JSON.stringify(merged),wi);for(const dep of deps)s.run("INSERT OR IGNORE INTO work_item_dependencies(work_item_id,dependency_id) VALUES(?,?)",wi,dep);}}for(const [nodeId,items] of itemsByNode)if(!incoming.has(nodeId)){s.run("UPDATE node_instances SET status='ready' WHERE id=?",instanceByNode.get(nodeId)!);for(const wi of items)s.run("UPDATE work_items SET status='pending_dispatch' WHERE id=?",wi);}s.run("UPDATE projects SET status='active',updated_at=?,version=version+1 WHERE id=?",now,project.id);audit(s,ctx.requestId,"project.started","快照流程并生成工作项","project",String(project.id));});sendSuccess(res,200,{projectId:project.id,status:"active"},ctx.requestId);};
  const runtime: NomosHandler = (_req,res,ctx)=>{const p=required<Dict>(db,"projects",ctx.params.id,ctx.requestId);const fv=p.flow_version_id?required<Dict>(db,"flow_versions",String(p.flow_version_id),ctx.requestId):null;const fi=db.get<Dict>("SELECT * FROM flow_instances WHERE project_id=?",ctx.params.id);const work=db.all<Dict>("SELECT * FROM work_items WHERE project_id=? ORDER BY created_at",ctx.params.id);const nodeInstances=fi?db.all<Dict>("SELECT * FROM node_instances WHERE flow_instance_id=? ORDER BY created_at",String(fi.id)).map((n)=>({id:n.id,flowNodeId:n.flow_node_id,status:n.status,workItemIds:work.filter((w)=>w.node_instance_id===n.id).map((w)=>w.id)})):[];const participantIds=[...new Set([String(p.owner_employee_id),...work.flatMap((w)=>w.assignee_employee_id?[String(w.assignee_employee_id)]:[])])];const participants=participantIds.map((id)=>db.get<Dict>("SELECT id,employee_no,name,type,status,schedulable,primary_position_id,connection_profile_id,created_at,updated_at,version FROM employees WHERE id=?",id)).filter(Boolean);sendSuccess(res,200,{project:{id:p.id,name:p.name,goal:p.goal,ownerEmployeeId:p.owner_employee_id,status:p.status},flowSnapshot:fv?{flowVersionId:fv.id,versionLabel:fv.version_label,nodes:mapVersion(db,fv).nodes}:null,nodeInstances,workItems:work.map(mapWork),participants},ctx.requestId);};
  return {listFlows,addFlow,addVersion,validateVersion,publishVersion,listProjects,addProject,startProject,runtime};
}
